/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
German Shepard by Quaternius [CC-BY] (https://creativecommons.org/licenses/by/3.0/) via Poly Pizza (https://poly.pizza/m/Hssa6NPc6W)
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

import scene from '../assets/3d/dog.glb'

const Dog = ({ currentAnimation, ...props }) => {
    const group = useRef()
    const { nodes, materials, animations } = useGLTF(scene)
    const { actions } = useAnimations(animations, group)

    useEffect(() => {
        Object.values(actions).forEach((action) => action.stop());

        if (actions[currentAnimation]) {
            actions[currentAnimation].play();
        }
    }, [actions, currentAnimation]);

    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Root_Scene">
                <group name="RootNode">
                    <group name="AnimalArmature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                        <primitive object={nodes.Body} />
                        <primitive object={nodes.IKBackLegL} />
                        <primitive object={nodes.IKFrontLegL} />
                        <primitive object={nodes.IKBackLegR} />
                        <primitive object={nodes.IKFrontLegR} />
                    </group>
                    <skinnedMesh
                        name="GermanShepherd"
                        geometry={nodes.GermanShepherd.geometry}
                        material={materials.Atlas}
                        skeleton={nodes.GermanShepherd.skeleton}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    />
                </group>
            </group>
        </group>
    )
}

export default Dog;
